// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demoBackEndQlTp2.Models;

namespace demoBackEndQlTp2.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20201214071713_initialDb")]
    partial class initialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("demoBackEndQlTp2.Models.QuanHuyen", b =>
                {
                    b.Property<int>("MaQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaTp");

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ThanhPhoMaTp");

                    b.HasKey("MaQuanHuyen");

                    b.HasIndex("MaTp");

                    b.HasIndex("ThanhPhoMaTp");

                    b.ToTable("quanHuyens");
                });

            modelBuilder.Entity("demoBackEndQlTp2.Models.ThanhPho", b =>
                {
                    b.Property<int>("MaTp")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTp")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaTp");

                    b.ToTable("thanhPhos");
                });

            modelBuilder.Entity("demoBackEndQlTp2.Models.XaPhuong", b =>
                {
                    b.Property<int>("MaXaPhuong")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaQuanHuyen");

                    b.Property<int?>("QuanHuyenMaQuanHuyen");

                    b.Property<string>("TenXaPhuong");

                    b.HasKey("MaXaPhuong");

                    b.HasIndex("MaQuanHuyen");

                    b.HasIndex("QuanHuyenMaQuanHuyen");

                    b.ToTable("xaPhuongs");
                });

            modelBuilder.Entity("demoBackEndQlTp2.Models.QuanHuyen", b =>
                {
                    b.HasOne("demoBackEndQlTp2.Models.ThanhPho", "ThanhPho")
                        .WithMany()
                        .HasForeignKey("MaTp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("demoBackEndQlTp2.Models.ThanhPho")
                        .WithMany("QuanHuyens")
                        .HasForeignKey("ThanhPhoMaTp");
                });

            modelBuilder.Entity("demoBackEndQlTp2.Models.XaPhuong", b =>
                {
                    b.HasOne("demoBackEndQlTp2.Models.QuanHuyen", "QuanHuyen")
                        .WithMany()
                        .HasForeignKey("MaQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("demoBackEndQlTp2.Models.QuanHuyen")
                        .WithMany("xaPhuongs")
                        .HasForeignKey("QuanHuyenMaQuanHuyen");
                });
#pragma warning restore 612, 618
        }
    }
}
